config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  resources :tasks
  resources :bookings
  resources :users
  resources :services
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  has_and_belongs_to_many :tasks
  has_many :bookings
  belongs_to :user

  def list_of_tasks
    task_names = []
    tasks.each do |task|
      task_names << task.name.downcase
    end
    task_names.join(", ")
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    authorize! :read, @services
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  def gardening
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.user = current_user
	authorize! :create, @service

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    authorize! :update, @service

    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    authorize! :destroy, @service

    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:name, :description, :begin_date, :end_date, :location, :price, :category, task_ids:[])
  end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(service) do |f| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_block">
    <div class="block_left">

      <!-- <%= f.label :category %>
      <%= f.select :category, [['IT'],['Gardening'],['Cleaning'],['Carpentry'], ['Electricity'], ['Plumbing']] %> -->
      <div class="field">
        <%= f.label "Gardening", :class => "h_category" %>
        <%= f.collection_check_boxes :task_ids, Task.where(category: "Gardening"), :id, :name do |b| %>
          <div class="collection-check-box">
            <table>
              <tr>
                <th><%= b.check_box %></th>
                <th><%= b.label %></th>
              </tr>
          </table>
          </div>
        <% end %>
      </div>
      <div class="field">
        <%= f.label "Electricity", :class => "h_category" %>
        <%= f.collection_check_boxes :task_ids, Task.where(category: "Electricity"), :id, :name do |b| %>
          <div class="collection-check-box">
            <table>
              <tr>
                <th><%= b.check_box %></th>
                <th><%= b.label %></th>
              </tr>
          </table>
          </div>
        <% end %>
      </div>
      <div class="field">
        <%= f.label "Cleaning", :class => "h_category" %>
        <%= f.collection_check_boxes :task_ids, Task.where(category: "Cleaning"), :id, :name do |b| %>
          <div class="collection-check-box">
            <table>
              <tr>
                <th><%= b.check_box %></th>
                <th><%= b.label %></th>
              </tr>
          </table>
          </div>
        <% end %>
      </div>
    </div>
    <div class="block_centre">
      <div class="field">
        <%= f.label "Carpentry", :class => "h_category" %>
        <%= f.collection_check_boxes :task_ids, Task.where(category: "Carpentry"), :id, :name do |b| %>
          <div class="collection-check-box">
            <table>
              <tr>
                <th><%= b.check_box %></th>
                <th><%= b.label %></th>
              </tr>
          </table>
          </div>
        <% end %>
      </div>
      <div class="field">
        <%= f.label "Plumbing", :class => "h_category" %>
        <%= f.collection_check_boxes :task_ids, Task.where(category: "Plumbing"), :id, :name do |b| %>
          <div class="collection-check-box">
            <table>
              <tr>
                <th><%= b.check_box %></th>
                <th><%= b.label %></th>
              </tr>
          </table>
          </div>
        <% end %>
      </div>
      <div class="field">
        <%= f.label "IT", :class => "h_category" %>
        <%= f.collection_check_boxes :task_ids, Task.where(category: "IT"), :id, :name do |b| %>
          <div class="collection-check-box">
            <table>
              <tr>
                <th><%= b.check_box %></th>
                <th><%= b.label %></th>
              </tr>
          </table>
          </div>
        <% end %>
      </div>

    </div>
    <div class="block_right">

      <div class="field">
        <%= f.label "Name for your service:" %>
        <%= f.text_field :name, :class => "field_right" %>
      </div>

      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, :class => "field_right" %>
      </div>

      <div class="field">
        <%= f.label "Available from:" %>
        <%= f.date_field :begin_date, :class => "field_right" %>
          <%= f.label "to:" %>
        <%= f.date_field :end_date, :class => "field_right" %>
      </div>

      <div class="field">
        <%= f.label :location %>
        <%= f.text_field :location, :class => "field_right" %>
      </div>

      <div class="field">
        <%= f.label :price %>
        <%= f.text_field :price, :class => "field_right" %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>



<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<% if can? :update, Service %>
  <%= render 'form', service: @service %>

  <%= link_to 'Show', @service %> |
<% else %>
  <p>Sign in to edit a service</p>
<% end %>

<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>Tasks</th>
      <th>Begin date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.category %></td>
        <td><%= service.list_of_tasks %></td>
        <td><%= service.begin_date.strftime("%d %B %Y") %></td>
        <td><%= service.end_date.strftime("%d %B %Y") %></td>
        <td><%= service.location %></td>
        <td><%= number_to_currency service.price, unit: '€ ' %></td>
        <td><%= service.user.email %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'New booking', new_booking_path(service) %>
        <td>
          <% if can? :update, service %>
            <%= link_to 'Edit', edit_service_path(service) %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, service %>
            <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<div class="form form-offer">
  <h1>I have a service to offer</h1>
<br>
<% if user_signed_in? %>
  <%= render 'form', service: @service %>
  <% else%>
  <%= link_to 'please log in to create a new service', new_user_session_path %>
  <br>
  <br>
  <% end %>
</div>
<br>
<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @service.user.email %>
<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Begin date:</strong>
  <%= @service.begin_date.strftime("%d %B %Y") %>
</p>

<p>
  <strong>End date:</strong>
  <%= @service.end_date.strftime("%d %B %Y") %>
</p>

<p>
  <strong>Location:</strong>
  <%= @service.location %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @service.price, unit: '€ ' %>
</p>

<p>
  <strong>Tasks:</strong>
  <%= @service.list_of_tasks %>
</p>



<% if can? :update, @service %>
  <%= link_to 'Edit', edit_service_path(@service) %> |
<% end %>
<%= link_to 'Back', services_path %>