config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  resources :tasks
  resources :bookings
  resources :users
  resources :services
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :service
  belongs_to :user

  validate :is_available

  def is_available
    overlapping = Booking.where("begin_date BETWEEN ? AND ? OR end_date BETWEEN ? AND ?", begin_date, end_date, begin_date, end_date).count

    return if overlapping == 0

    errors.add :booking, "this room is not available"
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
    authorize! :read, @bookings
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    if params[:format] == 0
      @service = Service.find_by(id: params[:booking][:service_id])
    else
      @service = Service.find_by(id: params[:format])
    end
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user

    authorize! :create, @booking

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    authorize! :update, @booking

    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    authorize! :destroy, @booking

    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:begin_date, :end_date, :total_price, :service_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :begin_date %>
    <%= f.date_select :begin_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

<% if defined? @service %>
  <div class="field">
    <%= f.hidden_field :service_id, :value => @service.id %>
  </div>
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<% if can? :update, Booking %>
  <%= render 'form', booking: @booking %>

  <%= link_to 'Show', @booking %> |
<% else %>
  <p>Sign in to edit a booking</p>
<% end %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Begin date</th>
      <th>End date</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.begin_date %></td>
        <td><%= booking.end_date %></td>
        <td><%= booking.total_price %></td>
        <td><%= link_to 'Show', booking %></td>
        <td>
          <% if can? :update, booking %>
            <%= link_to 'Edit', edit_booking_path(booking) %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, booking %>
            <%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking for <%= @service.name %></h1>

<p><%= @service.user.email %> will be available</p>
<p>from: <%= @service.begin_date.strftime("%d %B %Y") %></p>
<p>untill <%= @service.end_date.strftime("%d %B %Y") %></p>

<% if can? :create, Booking %>
  <%= render 'form', booking: @booking, service_id: params[:format] %>
<% else %>
  <p>Sign in to create a booking</p>
<% end %>

<%= link_to 'Back', bookings_path %>

<!-- <%= "blabla #{params[:format]}" %> -->

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservation</h1>

<p>
  <strong>Client:</strong>
  <%= @booking.user.email %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @booking.service.user.email %>
</p>

<p>
  <strong>Service:</strong>
  <%= @booking.service.name %>
</p>

<p>
  <strong>Begin date:</strong>
  <%= @booking.begin_date.strftime("%d %B %Y") %>
</p>

<p>
  <strong>End date:</strong>
  <%= @booking.end_date.strftime("%d %B %Y") %>
</p>
<p>
  <strong>Duur:</strong>
  <%= distance_of_time_in_words(@booking.begin_date, @booking.end_date) %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @booking.total_price %>
</p>

<!-- <% if can? :update, @booking %>
  <%= link_to 'Edit', edit_booking_path(@booking) %>
<% end %> -->
<%= link_to 'Back', bookings_path %>